import {
  createBlueGoblin,
  createGoldGobin,
  createGrayTroll,
  createGreenGoblin,
  createGreenTroll,
  createPirpleGoblin,
  createRedGoblin,
  createRedTroll,
} from "@/data/enemy/enemy_all";
import type { IBattleFloor } from "@/types/battle";

export const ALL_FLOOR: IBattleFloor[] = [
  {
    floor: 1,
    enemies: [createGreenGoblin(), createGreenGoblin(), createGreenGoblin()],
    isCleared: false,
    reward: { gold: 100, shardArtifact: 1 },
    isOpen: true,
  },
  {
    floor: 2,
    enemies: [createGreenGoblin(), createBlueGoblin(), createGreenGoblin()],
    isCleared: false,
    reward: { gold: 105, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 3,
    enemies: [createBlueGoblin(), createBlueGoblin(), createBlueGoblin()],
    isCleared: false,
    reward: { gold: 110, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 4,
    enemies: [createBlueGoblin(), createGreenGoblin(2), createBlueGoblin()],
    isCleared: false,
    reward: { gold: 115, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 5,
    enemies: [createBlueGoblin(), createGreenGoblin(2), createGoldGobin()],
    isCleared: false,
    reward: { gold: 120, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 6,
    enemies: [createBlueGoblin(), createRedGoblin(), createGoldGobin()],
    isCleared: false,
    reward: { gold: 125, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 7,
    enemies: [createGreenGoblin(2), createGreenGoblin(3), createGreenGoblin(2)],
    isCleared: false,
    reward: { gold: 130, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 8,
    enemies: [createGoldGobin(), createBlueGoblin(3), createGoldGobin()],
    isCleared: false,
    reward: { gold: 135, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 9,
    enemies: [createBlueGoblin(2), createBlueGoblin(2), createGoldGobin(2)],
    isCleared: false,
    reward: { gold: 140, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 10,
    enemies: [createPirpleGoblin(), createRedGoblin(2), createGoldGobin(2)],
    isCleared: false,
    reward: { gold: 145, shardSkill: 1 },
    isOpen: true,
  },
  {
    floor: 11,
    enemies: [createBlueGoblin(2), createGreenGoblin(4), createBlueGoblin(2)],
    isCleared: false,
    reward: { gold: 150, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 12,
    enemies: [createGreenGoblin(2), createBlueGoblin(4), createGoldGobin(2)],
    isCleared: false,
    reward: { gold: 155, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 13,
    enemies: [createPirpleGoblin(2), createGreenGoblin(3), createGoldGobin(3)],
    isCleared: false,
    reward: { gold: 160, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 14,
    enemies: [createGreenGoblin(3), createPirpleGoblin(2), createGreenGoblin(3)],
    isCleared: false,
    reward: { gold: 165, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 15,
    enemies: [createGreenGoblin(3), createBlueGoblin(3), createGoldGobin(3)],
    isCleared: false,
    reward: { gold: 170, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 16,
    enemies: [createGreenTroll(), createRedGoblin(2), createGreenTroll()],
    isCleared: false,
    reward: { gold: 175, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 16,
    enemies: [createGreenGoblin(4), createGrayTroll(), createGreenTroll()],
    isCleared: false,
    reward: { gold: 180, shardArtifact: 1 },
    isOpen: false,
  },
  {
    floor: 17,
    enemies: [createGreenTroll(), createGrayTroll(), createGoldGobin(3)],
    isCleared: false,
    reward: { gold: 185, shardSkill: 1 },
    isOpen: false,
  },
  {
    floor: 18,
    enemies: [createGreenTroll(), createRedTroll(), createGrayTroll()],
    isCleared: false,
    reward: { gold: 190, shardArtifact: 1 },
    isOpen: false,
  },
];
